### ISSUE TITLE
Buffer Empty

### ISSUE THREAD

**Issue by AOS55** [rll-research/url_benchmark#24]
Hi all, 

I'm trying to get some data to work with [ExORL](https://github.com/denisyarats/exorl), the buffer directory appears to be empty when saving the dataset. Were there any edits to urlb to generate the datasets used with ExORL? Thanks for all help :smiley:

I am running pre_training.py with: `python pretrain.py agent=aps domain=walker`

I believe this function should be saving the .npz buffer file:

 https://github.com/rll-research/url_benchmark/blob/bb98f0c6d78b3c467fb5a9fa5bbba3b7c0250397/replay_buffer.py#L18

**Comment by waterhorse1** [comment]
You can save the buffer by setting the save_snapshot as True. https://github.com/rll-research/url_benchmark/blob/bb98f0c6d78b3c467fb5a9fa5bbba3b7c0250397/pretrain.py#L88

**Comment by AOS55** [comment]
Uhhh got it cheers thanks for the help. Ill close the issue.

**Comment by waterhorse1** [comment]
@AOS55 I find a bug by setting save_snapshot = True, it will influence how the replay buffer is collected. And it will make the algorithm fail. So my choice is to implement one on my own.
