### ISSUE TITLE
ICM implementation

### ISSUE THREAD

**Issue by RobertMcCarthy97** [rll-research/url_benchmark#3]
Hi,

I had a few questions/comments regarding the [ICM implementation](https://github.com/rll-research/url_benchmark/blob/main/agent/icm.py).

Unlike the original "[Curiosity-driven exploration by self-supervised prediction](https://arxiv.org/abs/1705.05363)" paper, this implementation doesn't use the inverse dynamics model to learn a feature space in which forward predictions are made. In fact, it seems the inverse model is not being used for anything?

Also, is it problematic that the same encoder is being used (i) in the process of producing intrinsic rewards, and (ii) in the process of predicting intrinsic rewards (i.e. when predicting DDPG Q-values during pre-training)? I believe in the original paper the ICM module and the RL agent use a separate encoder.

I'm just wondering if you had any useful insights regarding these design choices. Apologies if I misinterpreted anything from the code or paper.

**Comment by MishaLaskin** [comment]
Those are all good pts from Denis, it is also worth noting that the Large
Scale Curiosity paper shows that random features are just as good as using
the inverse dynamics loss as representations of the CNN encoder.

This is further supported by RND which just learns a model over predictions
of a random CNN whose. Weights do not get updated. Overall, we played with
a number of configurations for each baseline and chose the ones that
produced the best results.

**Comment by RobertMcCarthy97** [comment]
Great, thanks very much for the interesting insights.

Thanks also for providing the nice code-base - I'm finding it very useful and easy to build upon!
