### ISSUE TITLE
How to use finetuning code?

### ISSUE THREAD

**Issue by VivianXue123** [rll-research/url_benchmark#8]
I would like to try out using finetuning after pretraining. I follow the instructions and use:

```
python finetune.py pretrained_agent=icm task=walker_run snapshot_ts=1000000 obs_type=states
```

Unfortunately, this gives me the following error:

```
Could not override 'pretrained_agent'.
To append to your config use +pretrained_agent=icm
Key 'pretrained_agent' is not in struct
    full_key: pretrained_agent
    object_type=dict\
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

What should I do here? Thanks!

**Comment by AOS55** [comment]
Try running with just `agent` i.e.
`python finetune.py agent=icm task=walker_run snapshot_ts=1000000 obs_type=states`, assuming you have already pretrained for a million steps on walker with icm agent

**Comment by AOS55** [comment]
Try running with just `agent` i.e.
`python finetune.py agent=icm task=walker_run snapshot_ts=1000000 obs_type=states`, assuming you have already pretrained for a million steps on walker with icm agent

**Comment by Kallin199** [comment]
I would like to finetune in the domain Jaco with the task of reach_top_left, i use the 
`python finetune.py task=Jaco_reach_top_left snapshot_ts=1000000 obs_type=states agent=apb reward_free=false
`
it warns me that raise f{task} not found, how should I test agent in this task? Thanks

**Comment by jsrimr** [comment]
Maybe README.md is misleading.
When we run 'pretrain.py' code, the snapshot is saved under 'models', not 'pretrained_models' directory.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/16870927/163787053-5f65d02c-ac8a-438c-acb9-b81e2b7f42bb.png">
